import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer.component";
import NavBar from "@/components/nav-bar.component";

const montserrat =  Montserrat({ 
  subsets: ["latin"],
  variable: '--font-mont'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className='font-mont bg-light w-full min-h-screen'>
          <NavBar/>
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
